package logicapps

import (
	"fmt"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/libre-devops/ldo-go-cli/internal/core/errs"
	"github.com/libre-devops/ldo-go-cli/internal/core/jsontext"
	"github.com/libre-devops/ldo-go-cli/internal/core/yamltext"
)

// Offline checks on workflow definitions, against the contract Azure enforces. These are
// not matters of taste; each is something the resource provider rejects, or that deploys
// cleanly and fails when the workflow runs:
//
//   - Every declared parameter needs a value by deploy time, or the engine returns
//     InvalidTemplate. $connections is the exception a deployment tool generates.
//     SecureString and SecureObject should arrive as inputs, so a secret never lands in the
//     definition.
//   - A connection is referenced by an arbitrary key, and that key has to match the one
//     wired at deploy time; nothing checks it until a run fails.
//   - A native Workflow dispatch action's target is checked when the caller is written
//     (NestedWorkflowNotFound), so a caller deploys after the workflow it calls.
//
// Nothing here touches the network.

// SecureTypes are the parameter types whose values must never be in a definition.
var SecureTypes = []string{"SecureString", "SecureObject"}

// Connections is the parameter a deployment tool generates from its connections input.
const Connections = "$connections"

var reference = regexp.MustCompile(`\$connections'\)\[\s*'([^']+)'\s*\]`)

// ParameterStatus is whether one declared parameter will have a value at deploy time, and
// from where: generated, supplied, default, wrapper, or none.
type ParameterStatus struct {
	Workflow    string `json:"workflow"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Secure      bool   `json:"secure"`
	Satisfied   bool   `json:"satisfied"`
	SatisfiedBy string `json:"satisfied_by"`
	Reason      string `json:"reason"`
	Source      string `json:"source"`
}

// Finding is something wrong with a definition: an error Azure rejects, or a warning.
type Finding struct {
	Workflow string `json:"workflow"`
	Severity string `json:"severity"`
	Rule     string `json:"rule"`
	Message  string `json:"message"`
	Source   string `json:"source"`
}

// Connection is a managed API connection a wrapper resolves, and how it authenticates.
type Connection struct {
	Workflow       string `json:"workflow"`
	Key            string `json:"key"`
	ConnectionName string `json:"connection_name"`
	ConnectionID   string `json:"connection_id"`
	ManagedAPIID   string `json:"managed_api_id"`
	Authentication string `json:"authentication"`
	Source         string `json:"source"`
}

// ManagedIdentity reports whether the connection signs in as the Logic App's managed
// identity.
func (c Connection) ManagedIdentity() bool { return c.Authentication == "ManagedServiceIdentity" }

// ConnectionReference is a $connections key the definition uses, where, and whether it is
// wired. Wired is nil for a bare definition: it carries no values, so whether the key
// resolves cannot be known from the file, and false would claim a fault not shown.
type ConnectionReference struct {
	Workflow string   `json:"workflow"`
	Key      string   `json:"key"`
	UsedBy   []string `json:"used_by"`
	Wired    *bool    `json:"wired"`
	Source   string   `json:"source"`
}

// DeployStep is a workflow's place in the deploy order: tier 0 first, then 1, and so on.
type DeployStep struct {
	Workflow  string   `json:"workflow"`
	Tier      int      `json:"tier"`
	DependsOn []string `json:"depends_on"`
	Source    string   `json:"source"`
}

// Difference is one JSON path where two definitions differ: changed, added (only in the
// second) or missing (only in the first).
type Difference struct {
	Path       string `json:"path"`
	Change     string `json:"change"`
	Reference  any    `json:"reference"`
	Difference any    `json:"difference"`
}

func verdictFor(document Document, name string, declaration yamltext.Ordered, secure, inWrapper bool, supplied []string) (bool, string, string) {
	switch {
	case name == Connections:
		return true, "generated", "generated by the deployment tool from its connections input"
	case slices.Contains(supplied, name):
		return true, "supplied", "supplied out of band as a deployment tool input"
	case has(declaration, "defaultValue"):
		return true, "default", "the declaration carries a defaultValue"
	case inWrapper && !secure:
		return true, "wrapper", "the " + document.Shape + " wrapper carries a value"
	case inWrapper && secure:
		return false, "none", "secure type: the wrapper's value is ignored on purpose; supply it as an input so the secret stays out of the definition"
	case document.Shape == "bare":
		return false, "none", "no defaultValue, and a bare definition has no wrapper values"
	}
	return false, "none", "no defaultValue, and the " + document.Shape + " wrapper has no value"
}

// ParameterStatuses is one record per declared parameter: satisfied, and by which source.
//
// A parameter is satisfied by being $connections (generated), by a name in supplied (a
// deployment tool's own parameters input), by a defaultValue, or by a value in the wrapper
// (never for a secure type, nor for a bare definition, whose parameters block is its
// declarations).
func ParameterStatuses(document Document, supplied []string) []ParameterStatus {
	var found []ParameterStatus
	for _, pair := range document.Declarations() {
		declaration := object(pair.Value)
		kind := text(declaration, "type")
		secure := slices.Contains(SecureTypes, kind)
		satisfied, by, reason := verdictFor(document, pair.Key, declaration, secure, has(document.ParameterValues, pair.Key), supplied)
		found = append(found, ParameterStatus{Workflow: document.Name, Name: pair.Key, Type: kind, Secure: secure, Satisfied: satisfied,
			SatisfiedBy: by, Reason: reason, Source: document.Source})
	}
	return found
}

// CheckOptions are what a deployment brings: parameters it supplies, connections it wires,
// and a trigger it calls back.
type CheckOptions struct {
	Supplied        []string
	Connections     []string
	CallbackTrigger string
}

// Check is every offline finding for document, errors first.
//
// Errors (the deploy is rejected): a parameter with no value; a supplied parameter the
// definition does not declare; connections wired to a definition without a $connections
// declaration; a callback trigger the definition does not have. Warnings (it deploys, then
// surprises you): no triggers; no actions; a $connections declaration with nothing wired.
func Check(document Document, opts CheckOptions) []Finding {
	var found []Finding
	add := func(severity, rule, message string) {
		found = append(found, Finding{Workflow: document.Name, Severity: severity, Rule: rule, Message: message, Source: document.Source})
	}
	for _, status := range ParameterStatuses(document, opts.Supplied) {
		if !status.Satisfied {
			add("error", "parameter-has-no-value", fmt.Sprintf("parameter '%s' (%s) has no value: %s", status.Name, pyNone(status.Type), status.Reason))
		}
	}
	for _, name := range opts.Supplied {
		if !has(document.Declarations(), name) {
			add("error", "supplied-parameter-not-declared", fmt.Sprintf("parameter '%s' is supplied but not declared: the definition is "+
				"the contract, and values only fill it", name))
		}
	}
	declared := has(document.Declarations(), Connections)
	switch {
	case len(opts.Connections) > 0 && !declared:
		add("error", "connections-not-declared", fmt.Sprintf("%d connection(s) are wired, but the definition declares no $connections parameter",
			len(opts.Connections)))
	case len(opts.Connections) == 0 && declared:
		add("warning", "connections-unwired", "the definition declares $connections, but no connections are wired to it")
	}
	shapeFindings(document, opts.CallbackTrigger, add)
	sort.SliceStable(found, func(a, b int) bool { return found[a].Severity == "error" && found[b].Severity != "error" })
	return found
}

// pyNone is text as Python's formatting shows a value that may be None.
func pyNone(text string) string {
	if text == "" {
		return "None"
	}
	return text
}

func shapeFindings(document Document, callback string, add func(severity, rule, message string)) {
	var triggers []string
	for _, pair := range document.Triggers() {
		triggers = append(triggers, pair.Key)
	}
	if len(triggers) == 0 {
		add("warning", "no-trigger", "the definition has no triggers, so nothing can start it")
	}
	if callback != "" && !slices.Contains(triggers, callback) {
		listed := strings.Join(triggers, ", ")
		if listed == "" {
			listed = "none"
		}
		add("error", "callback-trigger-not-found", fmt.Sprintf("callback trigger '%s' is not in the definition (triggers: %s)", callback, listed))
	}
	if len(document.Actions()) == 0 {
		add("warning", "no-actions", "the definition has no actions, so it does nothing when it runs")
	}
}

// ConnectionsOf is the connections a wrapper resolves; none for a bare definition.
func ConnectionsOf(document Document) []Connection {
	var found []Connection
	for _, pair := range object(get(get(document.ParameterValues, Connections), "value")) {
		detail := object(pair.Value)
		name := text(detail, "connectionName")
		if name == "" {
			name = pair.Key
		}
		found = append(found, Connection{Workflow: document.Name, Key: pair.Key, ConnectionName: name, ConnectionID: text(detail, "connectionId"),
			ManagedAPIID: text(detail, "id"), Authentication: text(get(get(detail, "connectionProperties"), "authentication"), "type"),
			Source: document.Source})
	}
	return found
}

// ConnectionReferences is each $connections key the definition uses, from triggers and
// nested actions. Triggers count: a Sentinel incident trigger reaches for a connection key
// exactly as an action does.
func ConnectionReferences(document Document) []ConnectionReference {
	var wired map[string]bool
	if document.Shape != "bare" && document.ParameterValues != nil {
		if value := object(get(get(document.ParameterValues, Connections), "value")); value != nil {
			wired = map[string]bool{}
			for _, pair := range value {
				wired[pair.Key] = true
			}
		}
	}
	type used struct {
		path   string
		inputs any
	}
	var nodes []used
	for _, pair := range document.Triggers() {
		nodes = append(nodes, used{"triggers/" + pair.Key, get(pair.Value, "inputs")})
	}
	for _, node := range ActionNodes(document.Actions(), "") {
		nodes = append(nodes, used{node.Path, get(node.Action, "inputs")})
	}
	var keys []string
	usage := map[string][]string{}
	for _, node := range nodes {
		if node.inputs == nil {
			continue
		}
		for _, match := range reference.FindAllStringSubmatch(jsontext.Dumps(node.inputs, 0), -1) {
			if _, seen := usage[match[1]]; !seen {
				keys = append(keys, match[1])
			}
			if !slices.Contains(usage[match[1]], node.path) {
				usage[match[1]] = append(usage[match[1]], node.path)
			}
		}
	}
	found := make([]ConnectionReference, len(keys))
	for index, key := range keys {
		var state *bool
		if wired != nil {
			value := wired[key]
			state = &value
		}
		found[index] = ConnectionReference{Workflow: document.Name, Key: key, UsedBy: usage[key], Wired: state, Source: document.Source}
	}
	return found
}

// DeployOrder is the order a set of workflows must deploy in, from their dispatch actions.
//
// Only a native Workflow dispatch action makes a dependency, since only its target is
// resolved when the caller is written: a workflow that merely names a sibling does not.
// Tier 0 dispatches to nothing in the set; each other workflow is one tier above the
// highest it calls. A cycle is an error.
func DeployOrder(documents []Document) ([]DeployStep, error) {
	byName := map[string]Document{}
	var names []string
	for _, document := range documents {
		name := document.Name
		if name == "" {
			name = document.Source
		}
		if _, seen := byName[name]; seen {
			return nil, errs.Inputf("two definitions are both called '%s'", name)
		}
		byName[name] = document
		names = append(names, name)
	}
	depends := map[string][]string{}
	for _, name := range names {
		depends[name] = dispatchTargets(byName[name], name, names)
	}
	tiers := map[string]int{}
	remaining := slices.Clone(names)
	for tier := 0; len(remaining) > 0; tier++ {
		var ready []string
		for _, name := range remaining {
			if allIn(depends[name], tiers) {
				ready = append(ready, name)
			}
		}
		if len(ready) == 0 {
			sort.Strings(remaining)
			return nil, errs.Inputf("no deploy order exists: these workflows dispatch to each other in a cycle: %s", strings.Join(remaining, ", "))
		}
		for _, name := range ready {
			tiers[name] = tier
			remaining = slices.DeleteFunc(remaining, func(item string) bool { return item == name })
		}
	}
	sorted := slices.Clone(names)
	sort.SliceStable(sorted, func(a, b int) bool {
		if tiers[sorted[a]] != tiers[sorted[b]] {
			return tiers[sorted[a]] < tiers[sorted[b]]
		}
		return sorted[a] < sorted[b]
	})
	steps := make([]DeployStep, len(sorted))
	for index, name := range sorted {
		steps[index] = DeployStep{Workflow: name, Tier: tiers[name], DependsOn: depends[name], Source: byName[name].Source}
	}
	return steps, nil
}

func allIn(names []string, tiers map[string]int) bool {
	for _, name := range names {
		if _, done := tiers[name]; !done {
			return false
		}
	}
	return true
}

func dispatchTargets(document Document, name string, siblings []string) []string {
	var targets []string
	for _, node := range ActionNodes(document.Actions(), "") {
		if text(node.Action, "type") != "Workflow" {
			continue
		}
		if id := text(get(get(get(node.Action, "inputs"), "host"), "workflow"), "id"); id != "" {
			targets = append(targets, strings.ToLower(id))
		}
	}
	found := []string{}
	for _, sibling := range siblings {
		if sibling == name {
			continue
		}
		if slices.ContainsFunc(targets, func(target string) bool { return strings.HasSuffix(target, "/workflows/"+strings.ToLower(sibling)) }) {
			found = append(found, sibling)
		}
	}
	return found
}

// Compare is the JSON paths where two definitions differ, after unwrapping both.
// Unwrapping first means a code view export compares cleanly with an ARM GET of the same
// workflow, and a rendered template with what is deployed: drift review as a diff.
func Compare(reference, difference Document, parameterValues bool) []Difference {
	var found []Difference
	walk(orNil(reference.Definition), orNil(difference.Definition), "definition", &found)
	if parameterValues {
		walk(orNil(reference.ParameterValues), orNil(difference.ParameterValues), "parameters", &found)
	}
	return found
}

func orNil(value yamltext.Ordered) any {
	if value == nil {
		return nil
	}
	return value
}

func walk(left, right any, path string, found *[]Difference) {
	switch {
	case left == nil && right == nil:
		return
	case left == nil:
		*found = append(*found, Difference{path, "added", left, right})
		return
	case right == nil:
		*found = append(*found, Difference{path, "missing", left, right})
		return
	}
	leftObject, leftIsObject := left.(yamltext.Ordered)
	rightObject, rightIsObject := right.(yamltext.Ordered)
	if leftIsObject && rightIsObject {
		keys := map[string]bool{}
		for _, pair := range append(slices.Clone(leftObject), rightObject...) {
			keys[pair.Key] = true
		}
		var sorted []string
		for key := range keys {
			sorted = append(sorted, key)
		}
		sort.Strings(sorted)
		for _, key := range sorted {
			walk(get(leftObject, key), get(rightObject, key), path+"."+key, found)
		}
		return
	}
	leftList, leftIsList := left.([]any)
	rightList, rightIsList := right.([]any)
	if leftIsList && rightIsList {
		for index := 0; index < max(len(leftList), len(rightList)); index++ {
			var a, b any
			if index < len(leftList) {
				a = leftList[index]
			}
			if index < len(rightList) {
				b = rightList[index]
			}
			walk(a, b, fmt.Sprintf("%s[%d]", path, index), found)
		}
		return
	}
	if jsontext.Dumps(sortedValue(left), 0) != jsontext.Dumps(sortedValue(right), 0) {
		*found = append(*found, Difference{path, "changed", left, right})
	}
}

// sortedValue is value with every object's keys sorted, as json.dumps(sort_keys=True).
func sortedValue(value any) any {
	switch v := value.(type) {
	case yamltext.Ordered:
		copied := make(map[string]any, len(v))
		for _, pair := range v {
			copied[pair.Key] = sortedValue(pair.Value)
		}
		return copied
	case []any:
		items := make([]any, len(v))
		for index, item := range v {
			items[index] = sortedValue(item)
		}
		return items
	}
	return value
}

// WithParameterDefaults is the definition with each wrapper value copied onto its
// declaration as a default, and how many were added. That makes an export deployable on
// its own. $connections is left for the deployment tool to generate, and secure types are
// never copied: writing a secret into the definition is what they exist to avoid. The
// result carries the SOURCE estate's values; RewriteReferences re-points them.
func WithParameterDefaults(document Document, force bool) (yamltext.Ordered, int, error) {
	if document.Shape == "bare" {
		return nil, 0, errs.Inputf("%s is a bare definition: it has declarations but no values to copy", document.Source)
	}
	definition := copyOrdered(document.Definition)
	added := 0
	for index, pair := range definition {
		if pair.Key != "parameters" {
			continue
		}
		declarations := object(pair.Value)
		for at, declared := range declarations {
			declaration := object(declared.Value)
			if declared.Key == Connections || declaration == nil || slices.Contains(SecureTypes, text(declaration, "type")) ||
				(has(declaration, "defaultValue") && !force) {
				continue
			}
			entry := object(get(document.ParameterValues, declared.Key))
			if value, ok := entry.Get("value"); ok {
				declarations[at].Value = setKey(declaration, "defaultValue", copyValue(value))
				added++
			}
		}
		definition[index].Value = declarations
	}
	return definition, added, nil
}

// setKey is object with key set to value: in its place when it is there, else added last.
func setKey(object yamltext.Ordered, key string, value any) yamltext.Ordered {
	for index, pair := range object {
		if pair.Key == key {
			object[index].Value = value
			return object
		}
	}
	return append(object, yamltext.Pair{Key: key, Value: value})
}

func copyOrdered(value yamltext.Ordered) yamltext.Ordered {
	copied, _ := copyValue(value).(yamltext.Ordered)
	return copied
}

func copyValue(value any) any {
	switch v := value.(type) {
	case yamltext.Ordered:
		copied := make(yamltext.Ordered, len(v))
		for index, pair := range v {
			copied[index] = yamltext.Pair{Key: pair.Key, Value: copyValue(pair.Value)}
		}
		return copied
	case []any:
		items := make([]any, len(v))
		for index, item := range v {
			items[index] = copyValue(item)
		}
		return items
	}
	return value
}

// RewriteReferences is text with each literal find and replace applied, in the order
// given. Estate-specific references (subscription ids, resource group and connection
// names, instance URLs) live in the serialised JSON, so rewriting the text keeps
// everything else byte-identical. Put the most specific replacement first.
func RewriteReferences(source string, replacements [][2]string) (string, error) {
	for _, replacement := range replacements {
		if replacement[0] == "" {
			return "", errs.Inputf("a replacement needs something to find")
		}
		source = strings.ReplaceAll(source, replacement[0], replacement[1])
	}
	return source, nil
}
